version: "3.9"

services:
  nginx:
    image: nginx:1-alpine
    ports:
      - "80:80"
    depends_on:
      - blog
    volumes:
      - ./assets/nginx/default.conf:/etc/nginx/conf.d/default.conf

  blog:
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - "FLASK_SQLALCHEMY_DATABASE_URI=postgresql+psycopg2://username:passwd!@pg:5432/blog"
      - FLASK_SQLALCHEMY_TRACK_MODIFICATIONS=False
      - FLASK_SECRET_KEY
    # ports:
    #   - "8000:8000"
    depends_on:
      pg:
        condition: service_healthy
    deploy:
      mode: replicated
      replicas: 3

  pg:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: username
      POSTGRES_PASSWORD: passwd!
      PGDATA: /var/lib/postgresql/data/pgdata
    # ports:
    #   - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data/pgdata
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  db-data:
