FROM python:3.9-alpine AS base

FROM base AS build

# We need to build cffi, so we will use multi-stage build
RUN apk update && apk add gcc libc-dev make git libffi-dev openssl-dev python3-dev libxml2-dev libxslt-dev g++

WORKDIR /app

COPY ./requirements.txt ./

RUN pip install -r requirements.txt

#################################
FROM base AS prod

ENV PYTHONUNBUFFERED=1

WORKDIR /app

COPY --from=build /usr/local/lib/python3.9/site-packages/ /usr/local/lib/python3.9/site-packages/
COPY scripts/run.sh ./
COPY migrations ./migrations
COPY blog ./blog

EXPOSE 8000

CMD ["./run.sh"]
